version: '2'
services:
    mongodemo-app:
        image: mongodemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodemo-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=mongodemo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mongodemo-mongodb:
        extends:
            file: mongodb.yml
            service: mongodemo-mongodb
